/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CoNotificationItem {
    'author': string;
    'avatarURL': string;
    'content': string;
    'date': string;
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
    'status': string;
    'title': string;
    'url': string;
  }
  interface CoNotificationItemAttributes extends StencilHTMLAttributes {
    'author'?: string;
    'avatarURL'?: string;
    'content'?: string;
    'date'?: string;
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
    'status'?: string;
    'title'?: string;
    'url'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CoNotificationItem': Components.CoNotificationItem;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'co-notification-item': Components.CoNotificationItemAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLCoNotificationItemElement extends Components.CoNotificationItem, HTMLStencilElement {}
  var HTMLCoNotificationItemElement: {
    prototype: HTMLCoNotificationItemElement;
    new (): HTMLCoNotificationItemElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'co-notification-item': HTMLCoNotificationItemElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'co-notification-item': HTMLCoNotificationItemElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
